# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetUserPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='accreditation',
            field=models.IntegerField(default=0, verbose_name='Accreditation'),
        ),
        migrations.AddField(
            model_name='resetuserpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
