# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsuser',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentsuser',
            name='subscribed_until',
            field=models.DateField(null=True, verbose_name='End of your subscription '),
        ),
        migrations.AlterField(
            model_name='savecarduser',
            name='card_exp_date',
            field=models.DateField(editable=False),
        ),
    ]
