# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171019_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsuser',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
