# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_paymentsuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsuser',
            name='subscription',
            field=models.CharField(max_length=255, null=True, verbose_name='Type of subscription: '),
        ),
    ]
