# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_paymentsuser_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsuser',
            name='product',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsuser',
            name='subscription',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
