# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171002_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsuser',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Product'),
        ),
        migrations.AlterField(
            model_name='paymentsuser',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.Subscription'),
        ),
    ]
