# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171002_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.CharField(max_length=255, null=True, verbose_name='Type of product: '),
        ),
    ]
