# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsuser',
            name='status',
            field=models.CharField("Status of the payment: ", default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriber',
            field=models.DateTimeField(null=True, verbose_name='End of your subscription: '),
        ),
    ]
