# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20171005_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsuser',
            name='reference',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='resetuserpassword',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='savecarduser',
            name='card_available',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='savecarduser',
            name='card_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
