# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20171005_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.AddField(
            model_name='paymentsuser',
            name='subscribed_until',
            field=models.DateTimeField(null=True, verbose_name='End of your subscription '),
        ),
    ]
