# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20171005_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='savecarduser',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
