# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_savecarduser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='savecarduser',
            name='first_name',
            field=models.CharField(default='guillaume', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savecarduser',
            name='last_name',
            field=models.CharField(default='cassou', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
