import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models

from payment.models import Subscription, Product


class User(AbstractUser):
    username = models.CharField(max_length=255, unique=True, verbose_name="Username")
    email = models.EmailField(unique=True, verbose_name="Email Address")
    accreditation = models.IntegerField(default=0, verbose_name="Accreditation")  # To manage rights on the site
    subscriber = models.DateTimeField("End of your subscription: ", null=True)
    subscription = models.CharField("Type of subscription: ", max_length=255, null=True)
    product = models.CharField("Type of product: ", max_length=255, null=True)
    # payments = PaymentsUser(models.Model)
    # card = SaveCardUser(models.Model)


class ValidateUser(models.Model):
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class ResetUserPassword(models.Model):
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class PaymentsUser(models.Model):
    reference = models.CharField(max_length=255, unique=True, editable=False)  # Payment id generated by Payplug
    date = models.DateTimeField(auto_now=True)
    status = models.CharField("Status of the payment: ", default="", max_length=255, null=True)  # To manage errors
    error_message = models.CharField("Error message: ", default="", max_length=255, null=True)
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE, related_name="payments")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="payments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="payments")


class SaveCardUser(models.Model):
    card_id = models.CharField(max_length=255, editable=False)
    card_exp_date = models.DateTimeField(editable=False)
    card_available = models.BooleanField(default=True, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="card")
