# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('tva', models.IntegerField()),
                ('ht', models.IntegerField()),
                ('recurrent', models.BooleanField(default=False)),
                ('duration', models.IntegerField(verbose_name='duration of the subscription in days')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='payment.Subscription'),
        ),
    ]
