# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_product_recurent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='informations',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='recurent',
            new_name='recursive',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='informations',
            new_name='description',
        ),
    ]
