# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20171005_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recursive',
            new_name='recurrent',
        ),
    ]
